### PR TITLE
Disable RDB by default

### PR DESCRIPTION
**Pull request by hamadmarri**
It seems the RDB is not working correctly for everyone.

### CODE REVIEW

**Comment by groobybugs** [comment]
@hamadmarri Good day!!! just wanted to say that Cacule is awesome, thank you very much for develop it and I look forward to the day when RDB will also work as good as Cacule.

**Comment by acjones8** [comment]
I know this has already been merged, but for what it's worth, I'm using the version of CacULE with RDB straight from Xanmod's sources, and the only thing I had to do to get it working properly was to set kernel.sched_autogroup_enabled=0 . I can't confess to understand the specifics, but I can observe that with autogroup enabled, RDB causes periodic freezes that last for about 2-5 seconds, and the frequency seems to vary by load - under heavy load, it happens every 30 seconds or so, but without any load, only every 10 minutes or so.

But once I disable it, the freezes completely disappear and it works wonderfully with the default settings, it's actually slightly better on my old ThinkPad than regular CacULE (which already performs very well). I know there's a testing patch in the CacULE tree around autogroup, but I'm not sure if by default it's included in Xanmod - or if it is, perhaps it doesn't work as well for some reason. But if anyone's been struggling to get it working, that and making sure nohz excludes their first core (and its sibling if it's hyperthreaded) worked wonders for me at least.

And yeah, thank you so much @hamadmarri for your hard work! RDB is the best performing scheduler I've ever used on Linux, it (along with Xanmod as a whole) have breathed new life into my old laptop. It does a scarily good job of keeping the system interactive under high load, and as a Gentoo user, that's an absolute life saver as we often need to compile stuff in the background for extended periods (especially with the GentooLTO patchset, as LTOing adds 50-100% to the compile time for large applications). With RDB, I can now upgrade my system anytime, and I don't have to worry about it impacting performance when doing my regular work. It's really awesome to have that flexibility, and I want to thank you guys again for your efforts, for both CacULE and Xanmod, they've made a huge difference for me.

**Comment by groobybugs** [comment]
@acjones8 I will try it, and yes there is a problem in the cacule repository, in fact I tried the patch and basically almost everything in that thread (change knobs, patch, enable/disable rdb, etc ), and the only solution was disable rdb, I disabled the autogroup from Grub as they said in the thread (In my case doing that is even worse), to be honest I think I didn't set the autogroup to 0 and I don't know if setting it to 0 and disabling it from grub are different results, so I will try it!

And yes Cacule with RDB gives a great performance, but I use emulator in my daily work, not for gaming, for develop and when i open the emulator basically my pc complete freezes not for seconds, minutes!!!

**Comment by acjones8** [comment]
@groobybugs If it helps, these are all the values I have for the scheduler (which I set through sysctl):

```
kernel.sched_autogroup_enabled = 0
kernel.sched_cache_divisor = 1000000
kernel.sched_cache_factor = 13107
kernel.sched_cacule_yield = 1
kernel.sched_cfs_bandwidth_slice_us = 5000
kernel.sched_child_runs_first = 0
kernel.sched_deadline_period_max_us = 4194304
kernel.sched_deadline_period_min_us = 100
kernel.sched_energy_aware = 1
kernel.sched_interactivity_factor = 32768
kernel.sched_max_lifetime_ms = 22000
kernel.sched_rr_timeslice_ms = 100
kernel.sched_rt_period_us = 1000000
kernel.sched_rt_runtime_us = 950000
kernel.sched_schedstats = 0
kernel.sched_starve_divisor = 3000000
kernel.sched_starve_factor = 19660
kernel.sched_util_clamp_max = 1024
kernel.sched_util_clamp_min = 1024
kernel.sched_util_clamp_min_rt_default = 1024
```

And although you probably already have this, I also had to put this on my grub line: `nohz_full=2-3` Since we need core 0 to be excluded from nohz, and on my FX CPU at least, cores 0 and 1 go together.

With these settings, I don't get any odd pauses, although I must confess I don't have any emulators I use a lot. If it helps, is your emulator publicly available (like Desmume, snes9x, etc.)? If so, I'd be happy to give it a shot and see if I can replicate the problem on my end, it could very well be an application specific thing.

**Comment by groobybugs** [comment]
Hi again @acjones8, thanks for your help!
well basically I tried with the auto group = 0 and yes I have the same values for the scheduler, I've noticed the system is more responsive but unluckily it keeps freezing, but for short periods of time and is something specific (before the whole desktop freezed, and basically took minutes to recover) freezes like latte-dock ,the emulator or a background task like video/music playing.

Doing my daily day routine the freezes only happens when I am compiling code, and have the emulator open. I also set the nohz line in grub and noticed best response times, but it keeps 🥶, I use the Android emulator ( in Android SDK) and is a QEMU emulator. 
Something freezes when you are compiling something in the background, and tries to use the emulator.

Resume:
Xanmod+cacule = works
XM+cacule+RDB = system freezes
XM+cacule+RDB+patch= system freezes
XM+cacule+RDB+autogroup0= only specific app freezes

😢

**Comment by hamadmarri** [comment]
Hi @acjones8 

I am glad to hear that RDB is working great in your machine.

The problem with RDB is that it either performs best in some machines or performs really bad in others. For XanMod kernel which is more a generic kernel that should replaces the stock default kernel, RDB cannot be a default. It could effect negatively XanMod and CacULE. For example, see the Zen kernel people when they mistakenly experimented CacULE+RDB instead of stable CacULE only, and many people complained about it. Unfortunately zen didn't consulted me nor anyone who knows the details of CacULE developments. With many people having this fast-judging mentality, RDB is not preferable to be enabled by default. Only who had RDB worked good with their machine would enable it and compile it. I have tried my best to troubleshoot the issue why RDB on some machines performs bad, but no luck at all (not even a single hint).

XanMod has already different kernel verities (edge, rt, lts, cacule) which already confuses some people as I read in reddit. Adding one more flavor like xanmod-cacule-rdb would be a bad idea.

All what I can do is too keep RDB code in xanmod-cacule patch where you can enable it without dealing with the hassle of patching it.

There is another work that I am testing right now (https://github.com/hamadmarri/TT-CPU-Scheduler). It has some concepts of CacULE (hrrn policy), and extremely lightweight load balancer which is safer than RDB since the rules are simple and safe (based on number of tasks on cpus only) and only CPU0 does the check and manages loadbalancing to avoid unpredictable synchronous  locking throttling. I prefer the idea of one smart policeman controls the traffic in a cross rather than that everyone follows simple solid rules while being stupid. Also TT has auto detection for RT tasks to give them more boost.


Thank you

**Comment by groobybugs** [comment]
Hi @hamadmarri 

I would be happy to help test this new TT scheduler, I saw that you have the patch for xanmod 5.14, how can I share the results?

**Comment by hamadmarri** [comment]
> Hi @hamadmarri
> 
> I would be happy to help test this new TT scheduler, I saw that you have the patch for xanmod 5.14, how can I share the results?

Hi @groobybugs 

You can share the results as issues in TT repo.

Thank you so much

**Pull request merged**
